### ISSUE TITLE
Filter events by area (just pass area via query)

### ISSUE THREAD

**Issue by osfameron** [osfameron/pageboy#2]

**Comment by osfameron** [comment]
Some links:
- http://global.mapit.mysociety.org/
- http://davidcel.is/posts/distance-constraints-with-postgresql-and-postgis/ (squirrels!)
- http://www.postgresql.org/docs/current/static/earthdistance.html (simpler!)

**Comment by HakimCassimallyBBC** [comment]
First slice:
- add an "areas" table, to contain some info from mapit
- add _single_ (for now) foreign key from event

Omitting for now:
- m2m relationship
- hierarchy

**Comment by osfameron** [comment]
On review, this appears to be broken in demo.  Requires a test-case (I removed the feature spectest in favour of the Geo IP ones) and fix.
